version: '3'
services:
  envoy:
    build: envoy
    ports:
      - "9901:9901"
      - "50051:50051"
    depends_on:
      - app
    image: front-envoy:0.1
    volumes:
    - log_volume:/var/log/mtail
  app:
    build: app
    image: grpc-ruby:0.1
  mtail:
    ports:
      - "3903:3903"
    build: mtail
    image: mtail:0.1
    volumes:
      - log_volume:/var/log/mtail
  prometheus:
    ports:
      - "9090:9090"
    build: prometheus
    image: prom:0.1
    depends_on:
      - mtail
volumes:
    log_volume:
